import Head from "next/head";
import Image from "next/image";
import { IoIosLogOut, IoIosNotificationsOutline } from "react-icons/io";
import { IoPersonOutline, IoSearch } from "react-icons/io5";
import { LuMessagesSquare, LuTimer, LuUsers, LuWallet } from "react-icons/lu";
import { MdArrowForwardIos } from "react-icons/md";
import { RiHomeSmile2Line } from "react-icons/ri";
import { TbSettings } from "react-icons/tb";
import styles from "../styles/Home.module.scss";
import { TitleHeader } from "./components/atoms/TitleHeader";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.sidebar}>
          <div className={styles.colfirst}>
            <h2>S</h2>
            <div className={styles.iconmessage}>
              <LuMessagesSquare />
            </div>
          </div>
          <div className={styles.colsecond}>
            <div className={styles.active}>
              <RiHomeSmile2Line color="white" width={100} />
            </div>
            <div className={styles.icon}>
              <IoIosNotificationsOutline className={styles.iconsize} />
            </div>
            <div className={styles.icon}>
              <LuTimer />
            </div>
            <div className={styles.icon}>
              <LuUsers />
            </div>
            <div className={styles.icon}>
              <LuWallet />
            </div>
            <div className={styles.icon}>
              <TbSettings />
            </div>
          </div>
          <div className={styles.colthird}>
            <div className={styles.icon}>
              <IoPersonOutline />
            </div>
            <div className={styles.icon}>
              <IoIosLogOut />
            </div>
          </div>
        </div>
        <div className={styles.maincontent}>
          <div className={styles.header}>
            <div>
              <h2>Hello, Jhon .D</h2>
              <p>View and control your finances here!</p>
            </div>
            <div className={styles.icon}>
              <IoSearch />
            </div>
          </div>
          <div className={styles.contentfirst}>
            <div className={styles.stats}>
              <div className={styles.balance}>
                <div>Balance Statistics</div>
                <div>
                  <h1>$564</h1>
                </div>
                <div class={styles.coin}>
                  <Image src="/coins.png" width={50} height={50} />
                  <p>Your Total balance</p>
                </div>
                <hr />
                <p>Always see your earnings updates</p>
              </div>
              <div>Filter</div>
            </div>
            <div className={styles.cardnumber}>
              <div className={styles.topleft}>
                <h2>S.</h2>
              </div>
              <div className={styles.topright}>
                <h2>VISA</h2>
              </div>
              <div className={styles.bottomleft}>
                <h4>**********9238</h4>
                <h4>John Doe</h4>
              </div>
              <div className={styles.bottomright}>
                <h4>08/12</h4>
              </div>
            </div>
          </div>
          <div className={styles.contentsecond}>
            <div className={styles.listitems}>
              <TitleHeader text={"List of Items to Buy"} />
              <div className={styles.time}>
                <div>
                  <h3>02:00</h3>
                  <p>Sat, Aug 12</p>
                </div>
                <MdArrowForwardIos className={styles.icon} />
                <div>
                  <h3>05:00</h3>
                  <p>Sat, Sep 12</p>
                </div>
              </div>
            </div>
            <div className={styles.chats}>
              <TitleHeader text={"Ester Howard"} />
              <div className={styles.time}>
                <div>
                  <h3>02:00</h3>
                  <p>Sat, Aug 12</p>
                </div>
                <MdArrowForwardIos className={styles.icon} />
                <div>
                  <h3>05:00</h3>
                  <p>Sat, Sep 12</p>
                </div>
              </div>
            </div>
          </div>
          <div className={styles.contentthird}>
            <div className={styles.listitems}>
              <TitleHeader text={"Last Transactions"} />
              <div className={styles.time}>
                <div>
                  <h3>02:00</h3>
                  <p>Sat, Aug 12</p>
                </div>
                <MdArrowForwardIos className={styles.icon} />
                <div>
                  <h3>05:00</h3>
                  <p>Sat, Sep 12</p>
                </div>
              </div>
            </div>
            <div className={styles.chats}>
              <TitleHeader text={"Analytics"} />
              <div className={styles.time}>
                <div>
                  <h3>02:00</h3>
                  <p>Sat, Aug 12</p>
                </div>
                <MdArrowForwardIos className={styles.icon} />
                <div>
                  <h3>05:00</h3>
                  <p>Sat, Sep 12</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.infocontent}>
          <div className={styles.card1}>
            <TitleHeader text={"Experiences and incomes"} />
            <div className={styles.income}>
              <div className={styles.griditem1}>
                <p>Expense</p>
                <h4>75%</h4>
                <p>5.653</p>
              </div>
              <div className={styles.griditem2}>
                <hr />

                <h4>VS</h4>

                <hr />
              </div>
              <div className={styles.griditem3}>
                <p>Income</p>
                <h4>40%</h4>
                <p>3.871</p>
              </div>
            </div>
            <div className={styles.bar}>
              <div className={styles.bar1}></div>
              <div className={styles.bar2}></div>
            </div>
          </div>

          <div className={styles.card2}>
            <div className={styles.headercard}>
              <TitleHeader text={"Latest Spending"} />
              <div>...</div>
            </div>
            <div className={styles.item1}>
              <div className={styles.image}>
                <Image src={"/troli.png"} width={50} height={50} />
              </div>
              <div>
                <h5>Online Store</h5>
                <p>May 30, 2023 at 08:00 pm</p>
              </div>
            </div>
            <hr style={{ margin: "0px" }} />
            <div className={styles.item1}>
              <div className={styles.image}>
                <Image src={"/pay-hospital.png"} width={50} height={50} />
              </div>
              <div>
                <h5>Pay the hospital</h5>
                <p>May 30, 2023 at 08:00 pm</p>
              </div>
            </div>
            <hr style={{ margin: "0px" }} />
            <div className={styles.item1}>
              <div className={styles.image}>
                <Image src={"/tickets.png"} width={50} height={50} />
              </div>
              <div>
                <h5>Tickets</h5>
                <p>May 30, 2023 at 08:00 pm</p>
              </div>
            </div>
            <h4>View All </h4>
          </div>
          <div className={styles.card3}>
            <div className={styles.textheader}>
              <TitleHeader text={"Go To Premium"} />
            </div>
            <div className={styles.image}>
              <Image src={"/crown.png"} width={150} height={100} />
            </div>
            <h3>Need More Features?</h3>
            <span>Update your account to premium to get more features</span>
            <div className={styles.button}>
              <h6>Get Now</h6>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
